apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: angular7-pipeline1
  namespace: angular-sample-app
spec:
  tasks:
    - name: git-clone-1-23-0
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: https://github.com/abhishekvishnoi/sample-angular7.git
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone-1-23-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: my-workspace
    - name: buildah-1-23-0
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/angular-sample-app/angular7-app:latest
        - name: DOCKERFILE
          value: ./Containerfile
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - npm-build
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah-1-23-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: my-workspace
    - name: npm-build
      params:
        - name: PATH_CONTEXT
          value: .
        - name: ARGS
          value:
            - version
        - name: IMAGE
          value: >-
            registry.redhat.io/ubi9/nodejs-20@sha256:71a3810707370f30bc0958aea14c3a5af564a3962ae0819bf16fdde7df9b4378
        - name: dist_name
          value: build
      runAfter:
        - git-clone-1-23-0
      taskRef:
        kind: Task
        name: npm-build
      workspaces:
        - name: source
          workspace: my-workspace
  workspaces:
    - name: my-workspace
      optional: false
  params: []
  finally: []
